-- HMNS Fragrance Recommender — Seed Data
-- Run: wrangler d1 execute hmns-db --local --file=migrations/002_seed.sql

INSERT OR IGNORE INTO products
  (name, slug, type, price_idr, volume_ml, scent_family, scent_tags, scent_texture,
   gender, intensity, top_notes, heart_notes, base_notes, occasion_tags, character_tags,
   time_of_day, description, image_url, product_url, in_stock, is_active)
VALUES
  ('Alpha', 'alpha', 'edp', 320000, 100, 'Green Woody', '["Green", "Woody", "Citrus"]', 'fresh', 'masc', 'balanced', '["Citrus", "Grass"]', '["Cedarwood"]', '["Green Tea Essence"]', '["daily", "outdoor", "active", "work"]', '["adventurous"]', 'morning', 'HMNS'' very first perfume. Born from the essence of green tea. A fresh, calming, and timeless fragrance.', 'https://madeforhmns.com/cdn/shop/files/Alpha-1_cc059a43-5bfd-4d61-badb-02d63dd51037.png?v=1739624155', 'https://madeforhmns.com/products/alpha-100ml', 1, 1),
  ('Farhampton', 'farhampton', 'extrait', 369000, 100, 'Fougere Fruity', '["Fougere", "Fruity", "Warm"]', 'sharp', 'unisex', 'balanced', '["Bergamot", "Ripe Fruit"]', '["Lavender", "Orange Blossom"]', '["Labdanum", "Cedarwood", "Tonka Beans"]', '["daily", "work", "date"]', '["creative", "romantic"]', 'all-day', 'Inspired by How I Met Your Mother, Farhampton brings back warmth, love, and the memory of rain.', 'https://madeforhmns.com/cdn/shop/files/Farhampton-1_41adab17-d977-452e-aada-9558448bf258.png?v=1770277998', 'https://madeforhmns.com/products/farhampton-100ml-extrait-de-parfum', 1, 1),
  ('Addict', 'addict', 'edp', 369000, 100, 'Gourmand', '["Gourmand", "Floral", "Sweet"]', 'sweet', 'unisex', 'balanced', '["Berries"]', '["Red Rose", "Coffee"]', '["Patchouli", "Amber", "Tonka Beans"]', '["daily", "date", "evening"]', '["romantic", "playful"]', 'evening', 'Something that lingers like a memory you can''t let go. It''s tender, romantic, and quietly addictive.', 'https://madeforhmns.com/cdn/shop/files/Addict-100ml-1_4734d2f2-8511-456e-a959-d2d1968f3e6c.png?v=1741672596', 'https://madeforhmns.com/products/addict-100ml', 1, 1),
  ('Ambar Janma', 'ambar-janma', 'edp', 510000, 100, 'Citrusy Aromatic Woody', '["Citrus", "Aromatic", "Woody", "Floral"]', 'fresh', 'unisex', 'balanced', '["Lemon", "Lavender", "Grapefruit", "Cumin", "Bergamot", "Mandarin", "Pink Pepper", "Cardamom"]', '["Fig", "Rose", "Marine", "Hyacinth", "Rose Essence", "Lily of The Valley", "Black Tea", "Neroli"]', '["Patchouli", "Sandalwood", "Amberwood", "Suede", "Musky", "Vetiver"]', '["work", "event", "date"]', '["adventurous", "creative"]', 'all-day', 'Unlock a new spectrum of fragrance with the Impossible Scent. A dual-fragrance designed to be layered or worn solo.', 'https://madeforhmns.com/cdn/shop/files/Ambar-Janma-1_b9f2d48e-2d08-44c0-ae75-9bb7cecb562c.png?v=1739520040', 'https://madeforhmns.com/products/hmns-perfume-ambar-janma-manusia-harum', 1, 1),
  ('ORGSM', 'orgsm', 'edp', 323000, 100, 'Fruity Floral Oriental', '["Fruity", "Floral", "Oriental", "Sweet"]', 'warm', 'unisex', 'balanced', '["Red Apple"]', '["Rose", "Jasmine", "Peony"]', '["Vanilla Beans", "Amber"]', '["daily", "date", "evening"]', '["sensualist", "playful"]', 'all-day', 'Three world''s best-selling notes in a single bottle of perfume. Irresistible, warm, and universally loved.', 'https://madeforhmns.com/cdn/shop/files/O-1_8e4c5b72-2987-4739-96ea-cb94a867665a.png?v=1739515717', 'https://madeforhmns.com/products/orgsm', 1, 1),
  ('Darker Shade of ORGSM', 'darker-shade-of-orgsm', 'edp', 380000, 100, 'Oriental Ambery', '["Oriental", "Ambery", "Woody", "Spicy"]', 'warm', 'unisex', 'balanced', '["Orange Blossom", "Apple", "Pepper"]', '["Cypriol", "Caramel", "Patchouli"]', '["Vanilla Beans", "Cedarwood", "Amber", "Vetiver"]', '["evening", "date"]', '["sensualist"]', 'evening', 'Inspired by HMNS Darker Shade of ORGSM. Mysterious yet comforting â€” the seductive side of sweetness.', 'https://madeforhmns.com/cdn/shop/files/Darker-1_f56395ea-afc5-4f1f-9609-ae848d098b92.png?v=1739518105', 'https://madeforhmns.com/products/hmns-perfume-darker-shades-of-orgasm-eau-de-parfum', 1, 1),
  ('ORGSM Melting Temptation', 'orgsm-melting-temptation', 'edp', 380000, 100, 'Gourmand Oriental', '["Gourmand", "Oriental", "Sweet", "Creamy"]', 'sweet', 'unisex', 'balanced', '["Pear", "Apple", "Caramel"]', '["Woody", "Cocoa"]', '["Vanilla", "Amber", "Musk"]', '["daily", "date", "evening"]', '["sensualist", "playful"]', 'evening', 'Creamy, milky, and sweet sensations blend together in one bottle. Pure temptation.', 'https://madeforhmns.com/cdn/shop/files/Melting-1.png?v=1741679241', 'https://madeforhmns.com/products/orgsm-melting-temptation', 1, 1),
  ('Essence of the Sun', 'essence-of-the-sun', 'edp', 369000, 100, 'Floral Oriental', '["Floral", "Oriental", "Warm", "Citrus"]', 'warm', 'fem', 'balanced', '["Bergamot", "Coriander Seeds", "Pink Pepper"]', '["Tropical Flower", "Indian Jasmine Sambac", "Turkish Rose", "Tiare Flower", "Solar Accord"]', '["Vanilla Absolute", "Tonka Beans", "Ambrette", "Cedarwood"]', '["daily", "work", "date"]', '["romantic"]', 'morning', 'Born from the essence of the sun. A scent that feels like the first light of the day â€” luminous, warm, and alive.', 'https://madeforhmns.com/cdn/shop/files/EoS-1_62ecb5de-eb89-4dd7-85c9-d51150602276.png?v=1739624030', 'https://madeforhmns.com/products/essence-of-the-sun-eos-100ml-edp', 1, 1),
  ('Unrosed', 'unrosed', 'edp', 374000, 100, 'Floral', '["Floral", "Earthy", "Musk"]', 'soft', 'fem', 'balanced', '["Palmarosa"]', '["Earthy"]', '["Musk"]', '["daily", "work", "date"]', '["minimalist", "romantic"]', 'morning', 'You''ll think it''s rose, but it''s not. Palmarosa makes it floral in its own way â€” quiet, refined, unmistakably itself.', 'https://madeforhmns.com/cdn/shop/files/Unrosed-1_d2252e46-2d76-44b5-a026-3c4c3fa82b8b.png?v=1739515148', 'https://madeforhmns.com/products/unrosed', 1, 1),
  ('Unpatched', 'unpatched', 'edp', 398000, 100, 'Gourmand Woody', '["Gourmand", "Woody", "Sweet", "Floral"]', 'deep', 'unisex', 'balanced', '["Jasmine Sambac", "Vanilla Madagascar", "Chocolate"]', '["Caramel", "Akigalawood", "Rose"]', '["Tonka Beans Brazil", "Amber", "Musk"]', '["daily", "evening", "date"]', '["creative", "sensualist"]', 'all-day', 'The kind of scent that stays, and keeps getting better with time. Complex, layered, unforgettable.', 'https://madeforhmns.com/cdn/shop/files/Unpatched-1_ba38ec1b-533a-422f-b586-2737a1e61e89.png?v=1739517784', 'https://madeforhmns.com/products/hmns-perfume-unpatched', 1, 1),
  ('The Perfection', 'the-perfection', 'edp', 398000, 100, 'Aromatic Fougere', '["Aromatic", "Fougere", "Woody", "Spicy"]', 'sharp', 'masc', 'balanced', '["Bergamot", "Elemi", "Indonesian Clove", "Nutmeg"]', '["Lavender", "Tagetes", "Lily of the Valley", "Green Pear"]', '["Driftwood", "Sandalwood", "Leather", "Musk"]', '["work", "daily", "event"]', '["adventurous", "minimalist"]', 'morning', 'It took 145 trials to create this scent. A celebration of every try and every patience that led here.', 'https://madeforhmns.com/cdn/shop/files/Perfection-1_d940fb62-a1aa-4dbd-85fe-163d5a9775ca.png?v=1739520190', 'https://madeforhmns.com/products/hmns-perfume-the-perfection', 1, 1),
  ('The Prestige', 'the-prestige', 'edp', 398000, 100, 'Woody Spicy Ambery', '["Woody", "Spicy", "Ambery", "Green"]', 'deep', 'masc', 'balanced', '["Grapefruit", "Tobacco Leaves", "Pink Pepper Jungle Essence"]', '["Patchouli", "Geranium", "Orris"]', '["Tolu", "Vetiver", "Labdanum"]', '["work", "event", "date"]', '["sensualist", "adventurous"]', 'all-day', 'A perfume that celebrates achievement. The pride that comes after countless trials.', 'https://madeforhmns.com/cdn/shop/files/Prestige-1_69e5b189-f576-4f78-b865-08f7ca0fe872.png?v=1739516997', 'https://madeforhmns.com/products/hmns-perfume-the-prestige', 1, 1),
  ('Untitled Humans Aroma 01', 'untitled-humans-aroma-01', 'edp', 395000, 100, 'Woody', '["Woody", "Earthy", "Floral", "Vanilla"]', 'deep', 'unisex', 'balanced', '["Coriander", "Violet Leaves", "Ambrette"]', '["Figolide", "Velvet Note", "Rose Absolute"]', '["Sandalwood", "Cypriol", "Vanilla Jungle Essence"]', '["daily", "work", "outdoor"]', '["minimalist", "creative"]', 'all-day', 'We believe that people can be anything. This scent was made for that freedom, for humans who live beyond titles.', 'https://madeforhmns.com/cdn/shop/files/Aroma-1-A.jpg?v=1759742680', 'https://madeforhmns.com/products/untitled-humans', 1, 1),
  ('Untitled Humans Aroma 02', 'untitled-humans-aroma-02', 'edp', 385000, 100, 'Floral Musk', '["Floral", "Musk", "Soft", "Powdery"]', 'soft', 'fem', 'balanced', '["Star Anise", "Rose Absolute"]', '["Violet", "Orris"]', '["Musk Milk", "Cashmere"]', '["daily", "work", "date"]', '["minimalist", "romantic"]', 'morning', 'The kind of scent that makes you feel beautiful, without even trying. Soft, skin-close, and effortless.', 'https://madeforhmns.com/cdn/shop/files/Aroma-2-A_f61b6c0e-4d51-495b-8cc7-31946cc44480.png?v=1741589736', 'https://madeforhmns.com/products/untitled-humans-aroma-02', 1, 1),
  ('Elea', 'elea', 'mist', 185000, 250, 'Floral Green Musk', '["Floral", "Green", "Musk", "Citrus"]', 'fresh', 'fem', 'subtle', '["Grapefruit", "Bergamot", "Magnolia"]', '["Jasmine", "Tuberose", "Neroli"]', '["Ambrette", "Honey", "Musk"]', '["daily", "active", "outdoor"]', '["minimalist", "romantic"]', 'morning', 'A friend who''s always there for you. Light, breezy, and effortlessly present.', 'https://madeforhmns.com/cdn/shop/files/Elea-1_1e7ff652-e874-4d6c-b759-091732d60952.png?v=1739517484', 'https://madeforhmns.com/products/hmns-x-tsana-fragrance-mist-elea', 1, 1),
  ('Philea', 'philea', 'edp', 385000, 100, 'Floral Green Musk', '["Floral", "Green", "Musk", "Citrus"]', 'fresh', 'fem', 'balanced', '["Bergamot", "Magnolia", "Coriander Seed"]', '["Jasmine", "Mimosa Absolute", "Orange Blossom"]', '["Cashmeran", "Heliotrope", "Musk"]', '["daily", "work", "date"]', '["minimalist", "romantic"]', 'all-day', 'The kind of friend who grows with you, through doubt, through everything. The EDP version of Elea.', 'https://madeforhmns.com/cdn/shop/files/Philea-1_b51e1f84-3be4-43c9-8f42-b0fd304db3b3.png?v=1770278058', 'https://madeforhmns.com/products/hmns-perfume-philea-100ml', 1, 1),
  ('SORE Zena', 'sore-zena', 'mist', 185000, 250, 'Tropical Gourmand', '["Tropical", "Gourmand", "Sweet", "Fruity"]', 'sweet', 'fem', 'subtle', '["Mandarin", "Caramel", "Apple Blossom"]', '["Pineapple", "Coconut Milk", "Tropicalone"]', '["Sandalwood", "Virginia Cedar", "Vanilla"]', '["daily", "active", "outdoor"]', '["playful", "romantic"]', 'morning', 'Zena means ''wife.'' A reflection of warm and deeply loving. Tropical, sweet, and full of affection.', 'https://madeforhmns.com/cdn/shop/files/SORE-Zena-1.png?v=1752511559', 'https://madeforhmns.com/products/hmns-x-sore-fragrance-mist-zena', 1, 1),
  ('SORE Eterna', 'sore-eterna', 'edp', 385000, 100, 'Citrusy Floral Musk', '["Citrus", "Floral", "Musk", "Fruity"]', 'fresh', 'fem', 'balanced', '["Bergamot", "Orange", "Petit Grain"]', '["Ylang-ylang", "Rose", "Peach"]', '["Cedarwood", "Musk", "Sandalwood"]', '["daily", "work", "date"]', '["romantic"]', 'all-day', 'To love endlessly. This scent brings the warmth of love stories that never fade.', 'https://madeforhmns.com/cdn/shop/files/SORE-Eterna-1_293fc203-968a-41c8-abd6-bacd027e0c5f.png?v=1752510962', 'https://madeforhmns.com/products/hmns-perfume-sore-eterna-100ml', 1, 1),
  ('My 1st O', 'my-1st-o', 'mist', 139000, 250, 'Fruity Floral Oriental', '["Fruity", "Floral", "Oriental", "Sweet"]', 'sweet', 'unisex', 'subtle', '["Fresh Orange", "Lemon", "Raspberry", "Peach Blossom"]', '["Jasmine", "Coconut", "Rose Petals", "Caramel"]', '["Patchouli", "Vanilla Beans", "Sandalwood"]', '["daily", "active", "outdoor"]', '["playful"]', 'morning', 'Inspired by HMNS ORGSM. Playful and irresistibly fresh â€” your first love in a bottle.', 'https://madeforhmns.com/cdn/shop/files/My1stO-1_2dd205fd-fa60-4a34-ba1f-aeb80955f482.png?v=1739518215', 'https://madeforhmns.com/products/hmns-hair-body-mist-my-1st-o', 1, 1),
  ('Drops of Sunshine', 'drops-of-sunshine', 'mist', 145000, 250, 'Floral Oriental', '["Floral", "Oriental", "Warm", "Citrus"]', 'warm', 'fem', 'subtle', '["Bergamot", "Coriander", "Pink Pepper Jungle Essence"]', '["Jasmine", "Ylang-ylang", "Turkish Rose"]', '["Vanilla", "Tonka Bean", "Musk"]', '["daily", "active", "outdoor"]', '["playful", "romantic"]', 'morning', 'Inspired by HMNS Essence of the Sun. Bright, creamy, and full of warmth.', 'https://madeforhmns.com/cdn/shop/files/DoS-1_62235d0c-0235-4761-a58c-fc6071a16943.png?v=1739518596', 'https://madeforhmns.com/products/hmns-hair-body-mist-drop-of-sunshine', 1, 1),
  ('Another Rose', 'another-rose', 'hair', 195000, 250, 'Floral Musk', '["Floral", "Musk", "Soft", "Citrus"]', 'soft', 'fem', 'subtle', '["Bergamot", "Raspberry"]', '["Rose", "Lily of the Valley"]', '["Musk", "Amber"]', '["daily", "work", "date"]', '["romantic", "minimalist"]', 'all-day', 'Inspired by HMNS Unrosed. Soft, musky, and beautiful â€” for hair that leaves a trail.', 'https://madeforhmns.com/cdn/shop/files/Another-Rose-1.png?v=1747198492', 'https://madeforhmns.com/products/hmns-nourishing-hair-perfume-another-rose', 1, 1),
  ('Darker Shade of O', 'darker-shade-of-o', 'hair', 195000, 250, 'Oriental Ambery', '["Oriental", "Ambery", "Spicy", "Sweet"]', 'warm', 'unisex', 'subtle', '["Orange Blossom", "Red Apple", "Pepper"]', '["Cypriol", "Caramel", "Patchouli"]', '["Vanilla Beans", "Cedarwood", "Amber", "Vetiver"]', '["evening", "date"]', '["sensualist", "romantic"]', 'evening', 'The warm, mysterious side of love â€” a hair perfume version of the Darker Shade character.', 'https://madeforhmns.com/cdn/shop/files/Darker-Shade-1.png?v=1747199457', 'https://madeforhmns.com/products/hmns-nourishing-hair-perfume-darker-shade-of-o', 1, 1),
  ('Alpha Hyper Green', 'alpha-hyper-green', 'extrait', 525000, 100, 'Green Fougere', '["Green", "Fougere", "Woody", "Citrus"]', 'sharp', 'masc', 'bold', '["Lemon Oil", "Pink Pepper CO2", "Cactus Accord"]', '["Tuberose Absolute", "Lavender Absolute", "Ciste Absolute"]', '["Patchouli Oil Indonesia", "Vetiver Oil Java", "Moss"]', '["outdoor", "active", "event"]', '["adventurous"]', 'morning', 'A greener, bolder version of Alpha. The scent of bright citrus, aromatic florals, earthy woods â€” intensified.', 'https://madeforhmns.com/cdn/shop/files/HyperGreen1.jpg?v=1771993940', 'https://madeforhmns.com/products/hmns-hyper-green-extrait-de-parfum', 1, 1),
  ('O Hyper Bloom', 'o-hyper-bloom', 'extrait', 525000, 100, 'Fruity Oriental Ambery', '["Fruity", "Oriental", "Ambery", "Floral"]', 'warm', 'fem', 'bold', '["Apple", "Pineapple", "Caramel"]', '["Tuberose", "Jasmine", "Lactonic", "Maltol"]', '["Vanilla", "Balsam", "Amber", "Coffee"]', '["evening", "date", "event"]', '["sensualist", "playful"]', 'evening', 'Purest form of pleasure. The sensation of juicy fruits, blooming white florals, warm ambery â€” at full intensity.', 'https://madeforhmns.com/cdn/shop/files/HyperBloom1.jpg?v=1771993850', 'https://madeforhmns.com/products/hmns-hyper-bloom-extrait-de-parfum', 1, 1),
  ('EoS Hyper Nova', 'eos-hyper-nova', 'extrait', 525000, 100, 'Floral Oriental', '["Floral", "Oriental", "Warm", "Vanilla"]', 'warm', 'fem', 'bold', '["Bergamot", "Coriander Seed", "Cocoa Butter"]', '["Solar", "Jasmine", "Ylang-ylang"]', '["Sandalwood", "Vanilla", "Vetiver"]', '["evening", "date", "event"]', '["romantic", "sensualist"]', 'evening', 'A brilliant explosion of the sun. Luminous solar, creamy cocoa butter, powdery vanilla â€” the boldest version of Essence of the Sun.', 'https://madeforhmns.com/cdn/shop/files/HyperNova1.jpg?v=1771993642', 'https://madeforhmns.com/products/hmns-hyper-nova-extrait-de-parfum', 1, 1);

-- Placeholder admin user (replace password_hash before deploying)
INSERT OR IGNORE INTO admin_users (username, password_hash) VALUES ('admin', 'REPLACE_WITH_PBKDF2_HASH');